version: "3.5"

services:
  nginx:
    image: nginx 
    container_name: vista-nginx
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./front/dist:/usr/share/nginx/html"
      - "./log/nginx:/var/log/nginx"
    networks:
      - app-net 

  app:
    build: 
      context: . 
      dockerfile: ./docker/Dockerfile
    container_name: vista-app 
    restart: always 
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8081:8081"
    volumes:
      - "./background/configs:/configs"
      - "./background/certs:/etc/ssl/certs"
    networks:
      - app-net

  mysql:
    image: mysql:9.1.0
    container_name: vista-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      # - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./lib/mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"
    networks:
      - app-net

  redis:
    image: redis:7.4.1
    container_name: vista-redis 
    ports:
      - "6379:6379"
    networks:
      - app-net

  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    restart: always
    container_name: vista-zinc
    environment:
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "Complexpass#123"
    ports:
      - "4080:4080"
    volumes:
      - "./lib/zinc/data:/data"
    networks:
      - app-net

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z-cpuv1
    container_name: vista-minio 
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server --console-address ":9001" http://minio/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./lib/minio/data1:/data1"
      - "./lib/minio/data2:/data2"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge