run:
	npm config set registry https://registry.npmmirror.com \ 
	&& npm install \
	&& npm run dev

build:
	npm config set registry https://registry.npmmirror.com \
	&& npm install \
	&& npm run build
